# Generated by Django 5.2 on 2025-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='month',
            field=models.CharField(choices=[('01', 'September'), ('02', 'October'), ('03', 'November'), ('04', 'December'), ('05', 'January'), ('06', 'February'), ('07', 'March'), ('08', 'April'), ('09', 'May'), ('10', 'June'), ('11', 'July'), ('12', 'August')], help_text='payroll processing month', max_length=12),
        ),
    ]
